"""Create password manager tables

Revision ID: 4aab10a4b2ee
Revises: 
Create Date: 2025-09-29 12:32:56.449063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aab10a4b2ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Unique identifier for the user'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Unique username for login'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hashed password for authentication'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('folders',
    sa.Column('folder_id', sa.UUID(), nullable=False, comment='Unique identifier for the folder'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner of the folder'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Name of the folder'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('folder_id')
    )
    op.create_table('password_entries',
    sa.Column('entry_id', sa.UUID(), nullable=False, comment='Unique identifier for the password entry'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner of the password entry'),
    sa.Column('folder_id', sa.UUID(), nullable=True, comment='Folder containing this entry (optional)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Name/title of the password entry'),
    sa.Column('username', sa.String(length=100), nullable=True, comment='Username or email for the service'),
    sa.Column('password', sa.Text(), nullable=True, comment='Encrypted password'),
    sa.Column('website_url', sa.String(length=500), nullable=True, comment='URL of the website/service'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes about the entry'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.folder_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_entries')
    op.drop_table('folders')
    op.drop_table('users')
    # ### end Alembic commands ###
