name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install uv package manager
      uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb # v6
    
    - name: Cache uv dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
    
    - name: Install uv dependencies
      run: uv sync --dev

    - name: Run unit tests
      run: uv run pytest tests/unit -v

    - name: Run integration tests
      run: uv run pytest tests/integration -v